title: Linda Doyle 
author: Linda Doyle 
email: lsdoyle@pm.me # email for form submission, you also have to change it in _js/scripts.js
description: I know you've been thinking I'm a good girl. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://lindasdoy.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: linda_doyle_ # replace with your_twitter_username or comment to remove link from footer
github_username:  lindasdoyle # replace with your_github_username or comment to remove link from footer
instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
social:
  name: linda Doyle
  links:
    - https://twitter.com/linda_doyle_
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/lindoyle/
    - https://github.com/lindoyle

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-theme-cayman
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
